Noe/revoke from UI
ephemeraHQ/converse-app pull request #907
Opened 2024-10-03 15:20 UTC by nmalzieu

Implement revocation action from the UI (in Profile)

- cleanup evm utils
- rename existing web util (for tx frames)`useExternalProvider` to `useExternalSigner`
- implement a WalletPicker drawer UI, to select an external wallet to link to the app
- keep the wallet that was linked during onboarding into memory rather than forgetting it
- implement the `useExternalSigner` helper for react native using thirdweb
- implement a `useXmtpSigner` helper to get an external / privy signer that matches the XMTP client owner address
- implement the revoke method using that signer, to revoke other installations

Very excited about this one, this leads the way for transactional frames work next week!

2024-10-03 20:34 UTC, alexrisch commented on components/Drawer.tsx
> +  style?: any;
Can we avoid any here?

2024-10-03 20:35 UTC, alexrisch commented on components/Drawer.tsx
> +  style?: any;
```suggestion
  style?: ViewStyle;
```

2024-10-03 20:37 UTC, alexrisch commented on components/ExternalWalletPicker.tsx
> +      fontWeight: "700",
```suggestion
      fontWeight: "700",
      color: textPrimaryColor(colorScheme),
```

2024-10-03 20:37 UTC, alexrisch commented on components/ExternalWalletPicker.tsx
> +      fontSize: 14,
```suggestion
      fontSize: 14,
      color: textPrimaryColor(colorScheme),
```

2024-10-03 20:38 UTC, alexrisch commented on components/ExternalWalletPicker.tsx
> +        {wallets.length === 0 && <Text>No wallet detected</Text>}
Add to translations

2024-10-03 21:07 UTC, alexrisch requested changes
This is really great!
There's a few dark mode styles that need to be cleaned up and probably some word play from a product perspective, but I thin we can create an internal feature build to get some additional testing on it before releasing, but really amazing progress on this 😄

2024-10-04 07:47 UTC, saulmc commented
> This is really great! There's a few dark mode styles that need to be cleaned up and probably some word play from a product perspective, but I thin we can create an internal feature build to get some additional testing on it before releasing, but really amazing progress on this 😄

@alexrisch word play here: https://github.com/ephemeraHQ/converse-app/pull/916

2024-10-04 13:46 UTC, nmalzieu commented
@alexrisch I applied some corrections and launched build 2.0.3 internally

2024-10-10 13:37 UTC, alexrisch approved these changes
Approving, we will have a testing meeting later today, but should be good to merge if no issues arise

2024-10-10 13:37 UTC, merged