[#824] no export default eslint rule
ephemeraHQ/converse-app pull request #947
Opened 2024-10-07 18:35 UTC by thierryskoda

2024-10-07 23:33 UTC, alexrisch commented
You'll need to update the max-warnings of the lint script in the package.json to match the new warnings count

2024-10-07 23:34 UTC, alexrisch requested changes
You'll need to update the max-warnings of the lint script in the package.json to match the new warnings count

2024-10-08 13:26 UTC, technoplato approved these changes

2024-10-09 16:00 UTC, alexrisch approved these changes

2024-10-09 16:23 UTC, merged